pipeline{
	agent any
	stages {
		stage('Build'){
			steps{
				sh 'python -m py_compile src/main.py src/calc.py'
			}
		}
		stage('Test'){
   			steps{
				sh 'py.test --verbose --junit-xml test-reports/results.xml src/test_calc.py'
			}
			post {
				always {
					junit 'test-reports/results.xml'
				}
			}
		}
		stage('Dist...'){
			steps {
				sh 'pyinstaller --onefile src/main.py'
			}
			post {
				success {
					archiveArtifacts 'dist/main'
				}
			}
		}
	}
}
